# Project can be found here: github.com/achannarasappa/ticker
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-positions: true
interval: 5
currency: SEK
currency-summary-only: false
watchlist:
  - MSFT
  - BOKUS.ST
  - STORY-B.ST
  - SPOT
  - AAPL
  - EVO.ST
