# import = ['string',]
# working directory = "<string>"	# Does not work with different OS
general.live_config_reload = true

[window]
# position = "None" | { x = <integer>, y = <integer> } # (has no effect on Wayland)
padding = { x = 10, y = 10 }
decorations = "Full"			# None, Full
opacity = 0.8
blur = true
startup_mode = "Maximized"		# Windowed, Maximized, Fullscreen
title = "Alacritty"
dynamic_title = false
decorations_theme_variant = "None"	# None, Dark, Light
level = "Normal"			# Normal, AlwaysOnTop

[font]
normal = { family = "Source Code Pro", style = "Regular" }
bold = { family = "Source Code Pro", style = "Bold" }
italic = { family = "Source Code Pro", style = "Italic" }
bold_italic = { family = "Source Code Pro", style = "Bold Italic" }
size = 13

[colors]

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.cursor]
cursor = "#d65d0e"
text = "CellBackground"

[colors.selection]
text = "CellForeground"
background = "#d65d0e"

[colors.normal]
black   = "#282828"
blue    = "#458588"
cyan    = "#689d6a"
green   = "#98971a"
magenta = "#b16286"
red     = "#cc241d"
yellow  = "#d79921"
white   = "#a89984"

[colors.bright]
black   = '#928374'
blue    = '#83a598'
cyan    = '#8ec07c'
green   = '#b8bb26'
magenta = '#d3869b'
red     = '#fb4934'
yellow  = '#fabd2f'
white   = '#ebdbb2'

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
unfocused_hollow = true

[terminal]
#shell = { program = "pwsh", args = ["-WorkingDirectory $HOME",] }
shell = { program = "pwsh", args = [] }

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
    #{ key = "V", mods = "Control", action = "Paste" },
    #{ key = "C", mods = "Control", action = "Copy" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
