terminal.shell = "pwsh"
general.working_directory = "C:\\Users\\danie"
general.live_config_reload = true

[window]
padding = { x = 10, y = 10 }
decorations = "Full"
#decorations = "None"
title = "Alacritty"
dynamic_title = false
opacity = 1
blur = true
startup_mode = "Windowed"

[font]
size = 11

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors]

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
blue    = "#458588"
cyan    = "#689d6a"
green   = "#98971a"
magenta = "#b16286"
red     = "#cc241d"
yellow  = "#d79921"
white   = "#a89984"

[colors.bright]
black   = '#928374'
blue    = '#83a598'
cyan    = '#8ec07c'
green   = '#b8bb26'
magenta = '#d3869b'
red     = '#fb4934'
yellow  = '#fabd2f'
white   = '#ebdbb2'

[colors.selection]
background = "#d65d0e"
text = "CellForeground"

[colors.cursor]
cursor = "#d65d0e"
text = "CellBackground"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
    #{ key = "V", mods = "Control", action = "Paste" },
    #{ key = "C", mods = "Control", action = "Copy" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
]
