#!/bin/bash
# Author Daniel Bäckman

# Exit if it breaks
# set -e

packages() {
	{
	sudo apt install tmux 
	sudo apt install tldr 
	sudo apt install vim 
	sudo apt install openssh-server 
	sudo apt install dircolors 
	sudo apt install newsboat 
	} 2>/dev/null
}

clone() {
	{
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	git clone https://github.com/vifm/vifm-colors ~/.config/vifm/colors 
	} 2>/dev/null
}

link() {
	if ! [ -e $HOME/.config/newsboat ]
	then
		mkdir $HOME/.config/newsboat
	elif ! [ -e $HOME/.config/vifm ]
	then
		mkdir $HOME/.config/vifm
	elif ! [ -e $HOME/.ssh ]
	then
		mkdir $HOME/.ssh
	elif ! [ -e $HOME/.tmux ]
	then
		mkdir $HOME/.tmux
	elif ! [ -e $HOME/.vim ]
	then
		mkdir $HOME/.vim
	fi
	{
	ln -s $HOME/dotfiles/newsboat-config $HOME/.config/newsboat/config 
	ln -s $HOME/dotfiles/newsboat-urls $HOME/.config/newsboat/urls 
	ln -s $HOME/dotfiles/.tmux.conf $HOME/$filename 
	ln -s $HOME/dotfiles/.tmuxline $HOME/$filename 
	ln -s $HOME/dotfiles/.vimrc $HOME/$filename 
	ln -s $HOME/dotfiles/vifmrc $HOME/.config/vifm/$filename 
	ln -s $HOME/dotfiles/.vim-template.html $HOME/.vim/$filename 
	ln -s $HOME/dotfiles/.vim-template.bash $HOME/.vim/$filename 
	rm $HOME/.bashrc
	ln -s $HOME/dotfiles/.bashrc $HOME/$filename
	} 2>/dev/null
}

vimplug() {
	echo -ne '\n' | vim +PluginInstall +qall 2>/dev/null
}

tmuxplug() {
	./.tmux/plugins/tpm/scripts/install_plugins.sh 2>/dev/null
}

update() {
	sudo apt update
	sudo apt dist-upgrade -yy
	sudo apt autoremove -yy
}

dircolors() {
	if [ -e /usr/bin/dircolors ]; then
		/usr/bin/dircolors -p > $HOME/.dircolors
		sed -i 's/DIR 01;34/DIR 01;33/' $HOME/.dircolors
	else
		echo "Something broke"
	fi
}

leave() {
	exit
}

everything() {
	update
	packages
	clone
	link
	vimplug
	tmuxplug
	dircolors
	leave
}

begin() {
# Main menu
cat << _EOF_

Welcome to Fauen's install script!

What would you like to do?

Press the number of your choice:

	1. Update
	2. Install packages
	3. Clone repositories
	4. Link the config files
	5. Install tmux plugins
	6. Install vim plugins
	7. Setup dircolors
	8. Everything
	0. Exit

_EOF_

read -n 1 -s choice;
case $choice in
	1) update;;
	2) packages;;
	3) clone;;
	4) link;;
	5) tmuxplug;;
	6) vimplug;;
	7) dircolors;;
	8) everything;;
	0) leave;;
	*) echo "Not a valid choice, please try again...";sleep 2;clear;begin;;
esac
}

clear
begin
