#!/bin/bash
# Author Daniel Bäckman

# Exit if it breaks
# set -e

packages() {
	sudo apt install tmux 2>/dev/null
	sudo apt install tldr 2>/dev/null
	sudo apt install vim 2>/dev/null
	sudo apt install openssh-server 2>/dev/null
	sudo apt install dircolors 2>/dev/null
}

directories() {
	mkdir $HOME/.config/newsboat
	mkdir $HOME/.config/vifm
	mkdir $HOME/.ssh
	mkdir $HOME/.tmux
	mkdir $HOME/.vim
}

clone() {
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	git clone https://github.com/vifm/vifm-colors ~/.config/vifm/colors
}

link() {
	ln -s $HOME/dotfiles/newsboat-config $HOME/.config/newsboat/config
	ln -s $HOME/dotfiles/newsboat-urls $HOME/.config/newsboat/urls
	ln -s $HOME/dotfiles/.tmux.conf $HOME/$filename
	ln -s $HOME/dotfiles/.vimrc $HOME/$filename
	ln -s $HOME/dotfiles/vifmrc $HOME/.config/vifm/$filename
	ln -s $HOME/dotfiles/.vim-template.html $HOME/.vim/$filename
	ln -s $HOME/dotfiles/.vim-template.bash $HOME/.vim/$filename
	rm $HOME/.bashrc
	ln -s $HOME/dotfiles/.bashrc $HOME/$filename
}

vimplug() {
	echo -ne '\n' | vim +PluginInstall +qall
}

update() {
	sudo apt update
	sudo apt dist-upgrade -yy
	sudo apt autoremove -yy
}

dircolors() {
	if [ -x $(command -v dircolors) ];then
		dircolors -p > $HOME/.dircolors
		sed -i 's/DIR 01;34/DIR 01;33/' $HOME/.dircolors
#	else
#		echo "dircolors is not installed. "
	fi
}

leave() {
	exit
}

everything() {
	update
	directories
	packages
	clone
	link
	vimplug
	dircolors
	leave
}

begin() {
# Main menu
cat << _EOF_

Welcome to Fauen's install script!

What would you like to do?

Press the number of your choice:

	1. Update
	2. Create directories
	3. Install packages
	4. Clone repositories
	5. Link the config files
	6. Install vim plugins
	7. Setup dircolors
	8. Everything
	0. Exit

_EOF_

read -n 1 -s choice;
case $choice in
	1) update;;
	2) directories;;
	3) packages;;
	4) clone;;
	5) link;;
	6) vimplug;;
	7) dircolors;;
	8) everything;;
	0) leave;;
	*) echo "Not a valid choice, please try again...";sleep 2;clear;begin;;
esac
}

clear
begin
