#!/usr/bin/env bash
# Author Daniel "fauen" Bäckman
# https://github.com/fauen

# Aliases
if [[ $(uname) == "Darwin" && ! $(command -v lsd) ]]; then
	brew install lsd
fi

if [[ $(uname) == "Linux" && ! $(command -v lsd) ]]; then
	if [[ $(cat /proc/version) == *"ubuntu"* ]]; then
		sudo apt install lsd
	elif [[ $(cat /proc/version) == *"arch"* ]]; then
		sudo pacman -S lsd
	elif [[ $(cat /proc/version) == *"Red Hat"* ]]; then
		sudo dnf install lsd
	fi
fi

# ls tweaks
alias ls='lsd'
alias ll='ls -alF'
alias la='ls A'
alias l='ls -CF'

alias grep='grep --color=always'
alias myip='curl ip.backman.io'
alias hackmainframe='echo "[32m"; hd /dev/urandom'
alias stocks=stonks
alias weather=wttr
alias tmuxs="tmux new-session -s ${1}"

# Aliases for GitHub
alias ga='git add . --all'
alias gb='git branch'
alias gc='git commit -a'
alias gl='git log'
alias gp='git pull'
alias gs='git status'

# Aliases for updates
alias windows-update='sudo apt update; sudo apt upgrade -y; sudo apt autoremove'

# Aliases for vim
alias vimplug="vim +PlugInstall +qall"
alias vimwiki="vim +VimwikiIndex"
