#!/usr/bin/env bash
# Author Daniel "fauen" Bäckman
# https://github.com/fauen

copy() {
	pbcopy 2>/dev/null ||
	wl-copy 2>/dev/null ||
	clip.exe
	return 0
}

epoch() {
	case "$1" in
		--now)
			date +%s
			;;
		"")
			printf "%s\n" "Usage: epoch [--now] [TIMESTAMP]"
			printf "%s\n" "    --now	Show the current epoch timestamp."
			printf "%s\n" "    TIMESTAMP	Convert the given epoch timestamp to a human-readable date."
			;;
		*)
			if date -r 0 &>/dev/null; then
				# This is for macOS
				date -r "$1" "+%Y-%m-%d %H:%M:%S"
			else
				date -d @"$1" "+%Y-%m-%d %H:%M:%S"
				# This is for Linux
			fi
			;;
	esac
	return 0
}

fd() {
	find . -type d -iname "*$1*" 2>/dev/null
	return 0
}

ff() {
	find . -type f -iname "*$1*" 2>/dev/null
	return 0
}

gsall() {
	local original_dir=$(pwd)
	for dir in */; do
		if [[ -d "$dir" ]]; then
			echo -e "\n$(tput rev)entering folder: $dir $(tput sgr0)"
			cd "$dir"
			git status
			cd "$original_dir"
		fi
	done
	return 0
}

guall() {
	local original_dir=$(pwd)
	for dir in */; do
		if [[ -d "$dir" ]]; then
			echo -e "\n$(tput rev)entering folder: $dir $(tput sgr0)"
			cd "$dir"
			git pull
			cd "$original_dir"
		fi
	done
	return 0
}

myip() {
	case "$1" in
		-a)
			curl -sS "ipall.backman.io"
			;;
		-h|--help)
			printf "%s\n" "Usage: myip [-a] [--help]"
			printf "%s\n" "    -a		Get all ip information."
			printf "%s\n" "    --help    	Show this help message."
			;;
		*)
			curl -sS "ip.backman.io"
			;;
	esac
	return 0
}

nato() {
	local input="${1^^}"
	declare -A phonetic=(
		["A"]="Alpha" ["B"]="Bravo" ["C"]="Charlie" ["D"]="Delta" ["E"]="Echo"
		["F"]="Foxtrot" ["G"]="Golf" ["H"]="Hotel" ["I"]="India" ["J"]="Juliet"
		["K"]="Kilo" ["L"]="Lima" ["M"]="Mike" ["N"]="November" ["O"]="Oscar"
		["P"]="Papa" ["Q"]="Quebec" ["R"]="Romeo" ["S"]="Sierra" ["T"]="Tango"
		["U"]="Uniform" ["V"]="Victor" ["W"]="Whiskey" ["X"]="X-ray" ["Y"]="Yankee"
		["Z"]="Zulu"
		["0"]="Zero" ["1"]="One" ["2"]="Two" ["3"]="Three" ["4"]="Four"
		["5"]="Five" ["6"]="Six" ["7"]="Seven" ["8"]="Eight" ["9"]="Nine"
		)

	for (( i=0; i<${#input}; i++ )); do
		local char="${input:$i:1}"
		echo -n "${phonetic[$char]:-$char} "
	done
	echo
return 0
}

pushover() {
	if ! command -v curl &>/dev/null; then
		printf "%s\n" "Error: curl is not installed." >&2
		return 1
	else
		if [[ ! -v PUSHOVER_TOKEN && ! -v PUSHOVER_USER ]]; then
			printf "%s\n" "Error: PUSHOVER_TOKEN and PUSHOVER_USER environment variables are not set." >&2
			return 1
		else
			curl -sS \
			-X POST \
			-H "Content-Type: application/json" \
			-d '{"token":"'"$PUSHOVER_TOKEN"'","user":"'"$PUSHOVER_USER"'","message":"'"$1"'"}' \
			https://api.pushover.net/1/messages.json
			return 0
		fi
	fi
}

set-theme() {
	curl -L backman.io/theme | bash
	return 0
}

weather() {
	case "$1" in
		-c)
			if [[ -z "$2" ]]; then
				printf "%s\n" "No city specified after -c." >&2
				return 1
			fi
			curl -sS "wttr.in/${2}?m"
			;;
		-h|--help)
			printf "%s\n" "Usage: weather [-c CITY] [--help]"
			printf "%s\n" "    -c CITY	Get weather for the specified city."
			printf "%s\n" "    --help	Show this help message."
			;;
		*)
			curl -sS "wttr.in/?m"
			;;
	esac
	return 0
}

windows-update() {
	if [[ $(uname) == "Linux" ]]; then
		if [[ $(cat /etc/os-release) == *"fedora"* ]]; then
			sudo dnf update
		elif [[ $(cat /etc/os-release) == *"arch"* ]]; then
			sudo pacman -Syu
		elif [[ $(cat /etc/os-release) == *"ubuntu"* ]]; then
			sudo apt update && sudo apt upgrade -y && sudo apt autoremove
		fi
	elif [[ $(uname) == "Darwin" && $(command -v brew) ]]; then
		brew update && brew upgrade
	fi
}
