#!/usr/bin/env bash
# Author Daniel "fauen" Bäckman
# https://github.com/fauen

copy() {
	pbcopy 2>/dev/null ||
	wl-copy 2>/dev/null ||
	clip.exe
}

date-conv() {
	date -r $1 "+%Y-%m-%d %H:%M:%S"
}

myip() {
	if [ -z $1 ]; then
		curl -sS ip.backman.io
	else
		curl -sS ipall.backman.io
	fi
}

weather() {
	if [ -z $1 ]; then
		curl -sS wttr.in/?m
	else
		curl -sS wttr.in/${1}?m
	fi
}
