#!/usr/bin/env bash
# Author Daniel "fauen" Bäckman
# https://github.com/fauen

copy() {
	pbcopy 2>/dev/null ||
	wl-copy 2>/dev/null ||
	clip.exe
}

epoch() {
	date -r $1 "+%Y-%m-%d %H:%M:%S"
}

gsall() {
	local original_dir=$(pwd)
	for dir in */; do
		if [[ -d "$dir" ]]; then
			echo -e "\n$(tput rev)entering folder: $dir $(tput sgr0)"
			cd "$dir"
			git status
			cd "$original_dir"
		fi
	done
}

guall() {
	local original_dir=$(pwd)
	for dir in */; do
		if [[ -d "$dir" ]]; then
			echo -e "\n$(tput rev)entering folder: $dir $(tput sgr0)"
			cd "$dir"
			git pull
			cd "$original_dir"
		fi
	done
}

myip() {
	if [[ $1 == "-a" ]]; then
		curl -sS ipall.backman.io
	elif [[ $1 =~ ^(-h|--help)$ ]]; then
		printf "%s\n" "Usage: weather [-a] [--help]"
		printf "%s\n" "    -a		Get all ip information."
		printf "%s\n" "    --help    	Show this help message."
	else
		curl -sS ip.backman.io
	fi
}

weather() {
	if [[ "$1" == "-c" ]]; then
		if [[ -z "$2" ]]; then
			printf "%s\n" "No city specified after -c." >&2
			return 1
		fi
		curl -sS wttr.in/${2}?m
	elif [[ $1 =~ ^(-h|--help)$ ]]; then
		printf "%s\n" "Usage: weather [-c CITY] [--help]"
		printf "%s\n" "    -c CITY	Get weather for the specified city."
		printf "%s\n" "    --help	Show this help message."
	else
		curl -sS wttr.in/?m
	fi
}
