#!/usr/bin/env bash

# Author Daniel "fauen" Bäckman
# https://github.com/fauen

function prompter() {
	local EXIT="$?"
	PS1=""

	local NOCOL='\[\e[00m\]'
	local RED='\[\e[01;31m\]'
	local GRE='\[\e[01;32m\]'
	local BLU='\[\e[01;34m\]'
	local MAG='\[\e[01;35m\]'
	local WHI='\[\e[01;37m\]'
	
	if [ $EXIT != 0 ]; then
		PS1+="${GRE}\u@\h${NOCOL}:${MAG}\w/${NOCOL}\$ ${RED}>>>${NOCOL} "
	else
		PS1+="${GRE}\u@\h${NOCOL}:${MAG}\w/${NOCOL}\$ ${GRE}>>>${NOCOL} "
	fi
}

#PROMPT_COMMAND=prompter

# Preserve the default PROMPT_COMMAND for history timestamps
__default_prompt_command="${PROMPT_COMMAND}"
# Initialize starship
eval "$(starship init bash)"
# Restore the default prompt command behavior for history
PROMPT_COMMAND="${__default_prompt_command}${PROMPT_COMMAND}"
