#!/usr/bin/bash
# Author Daniel "fauen" Bäckman
# https://github.com/fauen

export PROMPT_COMMAND=prompter

function prompter() {
	local EXIT="$?"
	PS1=""

	local NOCOL='\[\e[00m\]'
	local RED='\[\e[01;31m\]'
	local GRE='\[\e[01;32m\]'
	local MAG='\[\e[01;35m\]'
	local WHI='\[\e[01;37m\]'
	
	if [ $EXIT != 0 ]; then
		PS1+="${GRE}\u@\h${NOCOL}:${MAG}\w/${NOCOL}\$ ${RED}>>>${NOCOL} "
	else
		PS1+="${GRE}\u@\h${NOCOL}:${MAG}\w/${NOCOL}\$ ${GRE}>>>${NOCOL} "
	fi
}
