#!/usr/bin/env bash
# This file is not tracked by git, so you can put your own personal environment variables here.

if [[ $(uname) == "Linux" ]]; then
	export EDITOR=vim
	export VISUAL=vim
	#export TERM=xterm-256color
fi

if [[ $(uname) == "Darwin" ]]; then
	#export PATH="/opt/homebrew/bin:$PATH"
	export BASH_SILENCE_DEPRECATION_WARNING=1
	export FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT=1
	export HOMEBREW_NO_ENV_HINTS=1
fi

export PUSHOVER_USER=""
export PUSHOVER_TOKEN=""

echo "Hello"
